GET http://localhost:4000/employees/1


###
DELETE http://localhost:4000/employees
Content-Type: application/json

{
    "id":4
}
###
post http://localhost:4000/employees
Content-Type: application/json

{
    "firstname":"suba",
    "lastname":"devi"
}

###
POST  http://localhost:5000/employees
Content-Type: application/json

{
    "firstname":"suba",
    "lastname":"devi"
}
